language: cpp
sudo: false

branches:
  except:
    - gh-pages

env:
    - CC=gcc-5 CXX=g++-5 BRANCH="master" FERRET="yes"
    - CC=clang CXX=clang++ BRANCH="master" FERRET="yes"
    - CC=gcc-5 CXX=g++-5 BRANCH="stable-4.10" FERRET="yes"
    - CC=clang CXX=clang++ BRANCH="stable-4.10" FERRET="yes"
    - CC=gcc-5 CXX=g++-5 BRANCH="master" FERRET="no"
    - CC=clang CXX=clang++ BRANCH="master" FERRET="no"
    - CC=gcc-5 CXX=g++-5 BRANCH="stable-4.10" FERRET="no"
    - CC=clang CXX=clang++ BRANCH="stable-4.10" FERRET="no"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - automake
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; export CC=gcc-4.8; fi
  - git clone -b $BRANCH --depth=2 https://github.com/gap-system/gap.git gap-git
  - pwd
  - ( cd gap-git && ./autogen.sh || echo no autogen)
  - ( cd gap-git && ./configure && make && make bootstrap-pkg-minimal V=1)
  - ( cd gap-git/pkg && wget https://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/atlasrep1r5p1.tar.bz2 && tar -xf atlasrep*bz2 )
  - ( cd gap-git/pkg && wget https://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/semigroups-3.0.16.tar.bz2 && tar -xf semigroups*bz2 )
  - ( cd gap-git/pkg && git clone --depth=2 https://github.com/gap-packages/io )
  - ( cd gap-git/pkg && git clone --depth=2 https://github.com/gap-packages/orb )
  - ln -s $(pwd) gap-git/pkg/images
  - ( cd gap-git/pkg/io && ./autogen.sh && ./configure && make V=1 )
  - ( if [ "$FERRET" = "yes" ]; then (cd gap-git/pkg && git clone --depth=2 https://github.com/gap-packages/ferret ); fi)
  - ( if [ "$FERRET" = "yes" ]; then (cd gap-git/pkg/ferret && ./autogen.sh && ./configure && make V=1 ); fi )

script:
  - gap-git/bin/gap.sh -A gap-git/pkg/images/tst/testall.g
#  - valgrind --trace-children=yes --suppressions=scripts/gap-suppressions.valgrind gap-git/bin/gap.sh -A gap-git/pkg/images/tst/testall.g
