language: cpp

branches:
  except:
    - gh-pages
    

before_install:
  - sudo add-apt-repository ppa:azumanga/gap -y
  - sudo apt-get update -y
  - sudo apt-get install gap-snapshot libgmp3-dev parallel valgrind -y


install:
  - mkdir gap-root && mkdir gap-root/pkg
  - cd gap-root/pkg && wget https://github.com/gap-system/ferret/releases/download/v0.5.0/ferret-0.5.0.tar.gz && tar xf ferret-0.5.0.tar.gz && cd ferret-0.5.0 && ./configure /opt/gap && make
  - ln -s $(pwd) gap-root/pkg/images

script:
  - /opt/gap/bin/gap.sh -A tst/testall.g

