language: c
sudo: false

env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_BUILD="json io profiling orb ferret"

branches:
  except:
    - gh-pages

matrix:
  include:
    - env: CC=gcc-5 CXX=g++-5 BRANCH="master" FERRET="yes"
      compiler: gcc-5
    - env: CC=clang CXX=clang++ BRANCH="master" FERRET="yes"
      compiler: clang
    - env: CC=gcc-5 CXX=g++-5 BRANCH="stable-4.10" FERRET="yes"
      compiler: gcc-5
    - env: CC=clang CXX=clang++ BRANCH="stable-4.10" FERRET="yes"
      compiler: clang
    - env: CC=gcc-5 CXX=g++-5 BRANCH="master" FERRET="no"
      compiler: gcc-5
    - env: CC=clang CXX=clang++ BRANCH="master" FERRET="no"
      compiler: clang
    - env: CC=gcc-5 CXX=g++-5 BRANCH="stable-4.10" FERRET="no"
      compiler: gcc-5
    - env: CC=clang CXX=clang++ BRANCH="stable-4.10" FERRET="no"
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - automake
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind

before_script:
  - export GAPROOT="$HOME/gap"
  - (cd $GAPROOT/pkg && git clone --depth=2 https://github.com/gap-packages/ferret )
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh
  - scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
 
