language: cpp
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind

install:
#  - git clone --depth=2 https://github.com/gap-system/gap.git gap-git
  - git clone --depth=2 -b stab-iterator-fix https://github.com/ChrisJefferson/gap.git gap-git
  - pwd
  - ( cd gap-git && ./configure --with-gmp=system && make && make bootstrap-pkg-minimal)
  - ( cd gap-git/pkg && wget http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/atlasrep1r5p0.tar.bz2 && tar -xf atlasrep*bz2 )
  - ( cd gap-git/pkg && wget http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/semigroups-2.7.4.tar.bz2 && tar -xf semigroups*bz2 )
  - ( cd gap-git/pkg && git clone --depth=2 https://github.com/gap-packages/io )
  - ( cd gap-git/pkg && git clone --depth=2 https://github.com/gap-packages/orb )
  - ( cd gap-git/pkg && git clone --depth=2 https://github.com/gap-packages/ferret )
  - ln -s $(pwd) gap-git/pkg/images
  - ( cd gap-git/pkg && ../bin/BuildPackages.sh )

script:
  - gap-git/bin/gap.sh -A gap-git/pkg/images/tst/testall.g

