dist: xenial
language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_CLONE="ferret"
    - GAP_PKGS_TO_BUILD="json io profiling orb ferret"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - parallel
    - valgrind

matrix:
  include:
    - env: CC=gcc CXX=g++ BRANCH="master" FERRET="yes"
      compiler: gcc
    - env: CC=clang CXX=clang++ BRANCH="master" FERRET="yes"
      compiler: clang
    - env: CC=gcc CXX=g++ BRANCH="stable-4.10" FERRET="yes"
      compiler: gcc
    - env: CC=clang CXX=clang++ BRANCH="stable-4.10" FERRET="yes"
      compiler: clang
    - env: CC=gcc CXX=g++ BRANCH="master" FERRET="no"
      compiler: gcc
    - env: CC=clang CXX=clang++ BRANCH="master" FERRET="no"
      compiler: clang
    - env: CC=gcc CXX=g++ BRANCH="stable-4.10" FERRET="no"
      compiler: gcc
    - env: CC=clang CXX=clang++ BRANCH="stable-4.10" FERRET="no"
      compiler: clang

branches:
  except:
    - gh-pages

before_script:
  - export GAPROOT="$HOME/gap"
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
 