name: images
version: 0.7.0
date: 19/10/2016
description: Minimal and Canonical images

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "ferret"
      version: ">= 0.7.0"
      url: "http://gap-packages.github.io/ferret/"

www: http://gap-packages.github.io/images/
readme: http://gap-packages.github.io/images/README
packageinfo: http://gap-packages.github.io/images/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/images/releases/download/v0.7.0/images-0.7.0.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
