name: images
version: 1.3.0
date: 2019-03-21
description: |
    Minimal and Canonical images

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/
    - name: Rebecca Waldecker
      url: http://conway1.mathematik.uni-halle.de/~waldecker/
    - name: Eliza Jonauskyte
      url: mailto:ej31@st-andrews.ac.uk

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "ferret"
      version: ">= 0.8.0"
      url: "https://gap-packages.github.io/ferret/"

www: https://gap-packages.github.io/images/
readme: README.md
packageinfo: https://gap-packages.github.io/images/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/images/releases/download/v1.3.0/images-1.3.0.tar.gz

abstract: |
    A package for finding minimal and canonical images in permutation groups

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
