name: images
version: 0.1
date: 14/10/2014
description: Minimal and Canonical images

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "ferret"
      version: ">= 0.4.1"
      url: "http://gap-system.github.io/ferret/"

www: http://gap-system.github.io/images/
readme: http://gap-system.github.io/images/README
packageinfo: http://gap-system.github.io/images/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-system/images/releases/download/v0.1/images-0.1.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
