# images, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("images02.tst");

# doc/combi.xml:25-33
gap> LoadPackage("images", false);
true
gap> n := 4;;
gap> row := [n+1..2*n];;  col := [2*n+1..3*n];;
gap> enc := m -> Combinatorial.WithColoring(
>        Combinatorial.Matrix2D(m, row, col), [[1..n], row, col]);;
gap> klein := [[1,2,3,4],[2,1,4,3],[3,4,1,2],[4,3,2,1]];;

# doc/combi.xml:43-53
gap> klein2 := [[3,1,2,4],[1,3,4,2],[2,4,3,1],[4,2,1,3]];;
gap> z4 := [[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]];;
gap> can1 := CanonicalImage(SymmetricGroup(3*n), enc(klein), OnFundamental);;
gap> can2 := CanonicalImage(SymmetricGroup(3*n), enc(klein2), OnFundamental);;
gap> can3 := CanonicalImage(SymmetricGroup(3*n), enc(z4), OnFundamental);;
gap> can1 = can2;
true
gap> can1 = can3;
false

# doc/combi.xml:59-64
gap> mat := [[1,2,3,4],[1,4,3,2],[1,2,4,3],[4,2,1,3]];;
gap> fullm := Combinatorial.Matrix2D(mat, [1..4], [1..4]);;
gap> CanonicalImagePerm(SymmetricGroup(4), fullm);
(1,4,3,2)

#
gap> STOP_TEST("images02.tst", 1);
