LoadPackage("images", false);
LoadPackage("atlas", false);

##########################################################################
## Minimal Image checking functions
##########################################################################

makeRowColumnSymmetry := function(x,y)
    local perms,i,j,l;
    perms := [];

    for i in [1..(x-1)] do
        l := [1..x*y];
        for j in [1..y] do
            l[i    +(j-1)*x] := (i+1) + (j-1)*x;
            l[(i+1)+(j-1)*x] := i     + (j-1)*x;
        od;
        Append(perms, [PermList(l)]);
    od;

    for j in [1..(y-1)] do
        l := [1..x*y];
        for i in [1..x] do
            l[i+ j*x]    := i + (j-1)*x;
            l[i+(j-1)*x] := i + j*x;
        od;
        Append(perms, [PermList(l)]);
    od;
    return Group(perms);
end;;

# A transitive group on [1..size] from the libraries
randomBaseGroup := function(size)
    if size = 1 then
        return Group(());
    elif Random([false, true]) then
        return PrimitiveGroup(size, Random([1..NrPrimitiveGroups(size)]));
    else
        return TransitiveGroup(size, Random([1..NrTransitiveGroups(size)]));
    fi;
end;;

# A group moving at most [1..size], randomly relabelled: a library group,
# a direct product of library groups on a random split of the points, or
# the subgroup generated by a random subset of such a product's generators
# (which is where the more unusual groups come from)
randomGroup := function(size)
    local style, parts, left, p, g, gens;
    style := Random([1..4]);
    if style <= 2 or size < 4 then
        g := randomBaseGroup(size);
    else
        parts := [];
        left := size;
        while left > 0 do
            p := Random([1..left]);
            Add(parts, p);
            left := left - p;
        od;
        g := DirectProduct(List(parts, randomBaseGroup));
        if style = 4 then
            gens := Filtered(GeneratorsOfGroup(g), x -> Random([1..3]) > 1);
            g := Group(gens, ());
        fi;
    fi;
    return g ^ Random(SymmetricGroup(size));
end;;


allTinyPrimitiveGroups := function(size)
    return Union(List([1..size], x -> List([1..NrPrimitiveGroups(x)], y -> PrimitiveGroup(x,y))));
end;;

if not IsBound(FERRET_TEST_LIMIT) then
    FERRET_TEST_LIMIT := rec(count := 100, groupSize := 8);
fi;
# Above this size skip the checks which enumerate the whole group
# (the brute-force oracle and the generic Stabilizer call)
if not IsBound(FERRET_TEST_LIMIT.bruteForceLimit) then
    FERRET_TEST_LIMIT.bruteForceLimit := 50000;
fi;

# We use our own Random Transformation function, to
# get transformations where the result can be > size
cajRandomTransformation := function(size)
    return Transformation([1..size],List([1..size], x -> Random([1..size*2])));
end;;

RandomSet:= function(len)
    return Set([1..Random([0..len])], x -> Random([1..len + 5]));
end;

RandomTupleSet := function(len)
    return List([1..Random([0..len])], x -> RandomSet(Random([0..len+2])));
end;

RandomSetSet := function(len)
    return Set([1..Random([0..len])], x -> RandomSet(Random([0..len+2])));
end;

CheckMinimalImageTest := function(g, o, action, minList)
    local good_min, nostab_min, slow_min, cpyg, rando, can_orig, can_rand, perm_orig, perm_rand, order, gp, can_nostab, small_list, minperm, stab, stab_min;
    cpyg := Group(GeneratorsOfGroup(g), ());
    good_min := MinimalImage(g, o, action);
    nostab_min := CanonicalImage(cpyg, o, action, rec(stabilizer := Group(()), result := GetImage, order := CanonicalConfig_Minimum));

    if good_min <> nostab_min then
      Print(GeneratorsOfGroup(g)," ",o, ":",action," disagree: ", [good_min, nostab_min], "\n");
    fi;

    # brute-force oracle, for groups small enough to enumerate
    if Size(g) <= FERRET_TEST_LIMIT.bruteForceLimit then
        slow_min := minList(List(g, p -> action(o,p)));
        if good_min <> slow_min then
          Print(GeneratorsOfGroup(g)," ",o, ":",action,":",minList," we found ", good_min, " right answer is: ", slow_min,"\n");
        fi;
    fi;

    if (good_min = o) <> IsMinimalImage(g, o, action) then
        Print(GeneratorsOfGroup(g), " ",o, " failure of GetBool\n");
    fi;

    # the minimal image must be a fixed point of the whole API
    if not IsMinimalImage(g, good_min, action) then
        Print(GeneratorsOfGroup(g), " ",o, " GetBool false on minimal image\n");
    fi;
    if MinimalImage(g, good_min, action) <> good_min then
        Print(GeneratorsOfGroup(g), " ",o, " minimal image not a fixed point\n");
    fi;

    minperm := MinimalImagePerm(g, o, action);
    if good_min <> action(o, minperm) or not minperm in g then
        Print(GeneratorsOfGroup(g), " ",o, " failure of GetPerm\n");
    fi;

    # every point of the orbit has the same minimal image
    if MinimalImage(g, action(o, Random(g)), action) <> good_min then
        Print(GeneratorsOfGroup(g), " ",o, " conjugate has a different minimal image\n");
    fi;

    # a user-supplied stabilizer must not change the answer (only the
    # OnPoints and OnSets paths consume one)
    if (action = OnPoints or action = OnSets)
       and Size(g) <= FERRET_TEST_LIMIT.bruteForceLimit then
        stab := Stabilizer(g, o, action);
        stab_min := CanonicalImage(cpyg, o, action,
            rec(stabilizer := stab, result := GetImage, order := CanonicalConfig_Minimum));
        if stab_min <> good_min then
            Print(GeneratorsOfGroup(g), " ",o, " wrong answer with supplied stabilizer\n");
        fi;
    fi;

    if action = OnSets and Length(good_min) > 0 then
        if IsMinimalImageLessThan(g, o, good_min, OnSets) <> MinImage.Equal then
            Print("IsMinimalImageLessThan = error", g, o, good_min,"\n");
        fi;
        small_list := List(good_min);
        small_list[Random([1..Length(good_min)])] := 999;
        small_list := Set(small_list);
        if IsMinimalImageLessThan(g, o, small_list, OnSets) <> MinImage.Smaller then
            Print("IsMinimalImageLessThan < error", g, o, small_list, "\n");
        fi;
        small_list := List(good_min);
        small_list[Random([1..Length(good_min)])] := -3;
        small_list := Set(small_list);
        if IsMinimalImageLessThan(g, o, small_list, OnSets) <> MinImage.Larger then
            Print("IsMinimalImageLessThan > error", g, o, small_list, "\n");
        fi;
    fi;
    
    rando := action(o, Random(g));
    for order in [CanonicalConfig_Fast, CanonicalConfig_Minimum, CanonicalConfig_MinOrbit, CanonicalConfig_MaxOrbit, CanonicalConfig_SingleMaxOrbit,
                  CanonicalConfig_RareOrbit, CanonicalConfig_RareRatioOrbit, CanonicalConfig_CommonOrbit, CanonicalConfig_CommonRatioOrbit,
                  CanonicalConfig_RareRatioOrbitFix, CanonicalConfig_CommonRatioOrbitFix,
                  CanonicalConfig_RareRatioOrbitFixPlusMin, CanonicalConfig_RareRatioOrbitFixPlusRare, CanonicalConfig_RareRatioOrbitFixPlusCommon,
                  CanonicalConfig_RareOrbitPlusMin, CanonicalConfig_RareOrbitPlusRare, CanonicalConfig_RareOrbitPlusCommon,
                  CanonicalConfig_FixedMinOrbit, CanonicalConfig_FixedMaxOrbit ] do

        # Static branch orderings are not supported for the pair action used
        # by transformations, permutations and partial permutations
        if order.branch = "static" and action = OnPoints and
           (IsTransformation(o) or IsPerm(o) or IsPartialPerm(o)) then
            continue;
        fi;

        can_orig := CanonicalImage(cpyg, o, action, rec(stabilizer := Group(()), order := order, result := GetImage));
        can_rand := CanonicalImage(cpyg, rando, action, rec(stabilizer := Group(()), order := order, result := GetImage));
        can_nostab :=  CanonicalImage(cpyg, rando, action, rec(stabilizer := Group(()), order := order, result := GetImage, disableStabilizerCheck := true));
        perm_orig := CanonicalImage(cpyg, o, action, rec(stabilizer := Group(()), order := order, result := GetPerm));
        perm_rand := CanonicalImage(cpyg, rando, action, rec(stabilizer := Group(()), order := order, result := GetPerm));

        if not(perm_orig in g and perm_rand in g and
               action(o, perm_orig) = can_orig and action(rando, perm_rand) = can_rand and
               can_orig = can_rand and can_orig = can_nostab) then
            Print(GeneratorsOfGroup(g), ":", order, ":", o, ":", rando, ":", can_orig, ":", can_rand, ":", can_nostab, "\n");
        fi;

        # GetBool must agree with GetImage: the canonical image is its own
        # canonical image and anything else is not. (Regression check: the
        # early-exit comparisons used to assume the minimum ordering and
        # returned spurious 'false' for the dynamic orderings.)
        if not CanonicalImage(cpyg, can_orig, action, rec(stabilizer := Group(()), order := order, result := GetBool)) then
            Print(GeneratorsOfGroup(g), ":", order, ":", o, " GetBool false on canonical image\n");
        fi;
        if can_orig <> o and CanonicalImage(cpyg, o, action, rec(stabilizer := Group(()), order := order, result := GetBool)) then
            Print(GeneratorsOfGroup(g), ":", order, ":", o, " GetBool true on non-canonical object\n");
        fi;
    od;

end;;

CheckCanonicalImageTest := function(g, o, action)
    local cpyg, rando, can_orig, can_rand, perm_orig, perm_rand;
    cpyg := Group(GeneratorsOfGroup(g), ());
    
    rando := action(o, Random(g));

    can_orig := CanonicalImage(cpyg, o, action);
    can_rand := CanonicalImage(cpyg, rando, action);
    perm_orig := CanonicalImagePerm(cpyg, o, action);
    perm_rand := CanonicalImagePerm(cpyg, rando, action);

    if not(perm_orig in g and perm_rand in g and
            action(o, perm_orig) = can_orig and action(rando, perm_rand) = can_rand and
            can_orig = can_rand) then
        Print(perm_orig, ":", perm_rand, "\n");
        Print(GeneratorsOfGroup(g), ":", ViewString(o), ":", ViewString(rando), ":", ViewString(can_orig), ":", ViewString(can_rand), "\n");
    fi;

    # the canonical image must be a fixed point
    if CanonicalImage(cpyg, can_orig, action) <> can_orig then
        Print(GeneratorsOfGroup(g), ":", ViewString(o), " canonical image not a fixed point\n");
    fi;

    # in tiny groups, check the whole orbit canonicalizes to one object
    if Size(g) <= 200 then
        if Length(Set(Elements(g), p -> CanonicalImage(cpyg, action(o, p), action))) <> 1 then
            Print(GeneratorsOfGroup(g), ":", ViewString(o),
                  " distinct canonical images over one orbit\n");
        fi;
    fi;
end;;


CheckMinimalImageTransformations := function()
    local i;
    CheckMinimalImageTest(Group(()), Transformation([]), OnPoints, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), Transformation([]), OnPoints, Minimum);
    CheckMinimalImageTest(Group(()), Transformation([1],[6]), OnPoints, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              cajRandomTransformation(Random([1..FERRET_TEST_LIMIT.groupSize + 2])), OnPoints, Minimum);
    od;
end;;

# Wow, hard-wired to only handle up to size 50. How horrible.
# But it's fine for now!
minListPP := function(l)
    local smallest, i;
    smallest := l[1];
    for i in l do
        if AsTransformation(i, 50) < AsTransformation(smallest, 50) then
            smallest := i;
        fi;
    od;
    return smallest;
end;


CheckMinimalImagePartialPerm := function()
    local i;
    CheckMinimalImageTest(Group(()), PartialPerm([]), OnPoints, minListPP);
    CheckMinimalImageTest(Group((1,2,3)), PartialPerm([]), OnPoints, minListPP);
    CheckMinimalImageTest(Group(()), PartialPerm([1],[6]), OnPoints, minListPP);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              RandomPartialPerm(Random([1..FERRET_TEST_LIMIT.groupSize + 2])), OnPoints, minListPP);
    od;
end;;

CheckMinimalImagePerm := function()
    local i, g;
    CheckMinimalImageTest(Group(()), PermList([]), OnPoints, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), PermList([]), OnPoints, Minimum);
    CheckMinimalImageTest(Group(()), PermList([3,2,1]), OnPoints, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        g := randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize]));
        if Random([false, true]) then
            # conjugating an element of the group itself: the common use
            CheckMinimalImageTest(g, Random(g), OnPoints, Minimum);
        else
            CheckMinimalImageTest(g,
                Random(SymmetricGroup(Random([1..FERRET_TEST_LIMIT.groupSize + 2]))), OnPoints, Minimum);
        fi;
    od;
end;;

CheckMinimalImagePoint := function()
    local i;
    CheckMinimalImageTest(Group(()), 1, OnPoints, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), 3, OnPoints, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), 7, OnPoints, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              Random([1..FERRET_TEST_LIMIT.groupSize + 2]), OnPoints, Minimum);
    od;
end;;


CheckMinimalImageSet := function()
    local i;
    CheckMinimalImageTest(Group(()), [], OnSets, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), [], OnSets, Minimum);
    CheckMinimalImageTest(Group(()), [1,2,3], OnSets, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize + 1])),
                              RandomSet(Random([1..FERRET_TEST_LIMIT.groupSize + 2])), OnSets, Minimum);
    od;
end;;

CheckMinimalImageTuple := function()
    local i;
    CheckMinimalImageTest(Group(()), [], OnTuples, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), [], OnTuples, Minimum);
    CheckMinimalImageTest(Group(()), [1,2,3], OnTuples, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              Shuffle(RandomSet(Random([1..FERRET_TEST_LIMIT.groupSize + 2]))), OnTuples, Minimum);
    od;
end;;

CheckMinimalImageTupleTransformation := function()
    local i;
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              List([1..Random([1..FERRET_TEST_LIMIT.groupSize/2])],
                                    x -> cajRandomTransformation(Random([1..FERRET_TEST_LIMIT.groupSize + 2]))), OnTuples, Minimum);
    od;
end;;

CheckMinimalImageTuplePerm := function()
    local i;
    CheckMinimalImageTest(Group(()), [()], OnTuples, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), [(1,2),(2,3)], OnTuples, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              List([1..Random([1..3])],
                                    x -> Random(SymmetricGroup(Random([1..FERRET_TEST_LIMIT.groupSize + 2])))), OnTuples, Minimum);
    od;
end;;

CheckMinimalImageSetSet := function()
    local i;
    CheckMinimalImageTest(Group(()), [[]], OnSetsSets, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), [[]], OnSetsSets, Minimum);
    CheckMinimalImageTest(Group(()), [[1,2,3]], OnSetsSets, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              RandomSetSet(Random([1..FERRET_TEST_LIMIT.groupSize + 2])), OnSetsSets, Minimum);
    od;
end;;

CheckMinimalImageTupleSet := function()
    local i;
    CheckMinimalImageTest(Group(()), [[]], OnTuplesSets, Minimum);
    CheckMinimalImageTest(Group((1,2,3)), [[]], OnTuplesSets, Minimum);
    CheckMinimalImageTest(Group(()), [[1,2,3]], OnTuplesSets, Minimum);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckMinimalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])),
                              RandomTupleSet(Random([1..FERRET_TEST_LIMIT.groupSize + 2])), OnTuplesSets, Minimum);
    od;
end;;


# The same options record must be usable for several calls, including after
# getStab has deposited the stabilizer into it
CheckOptionsRecordReuse := function()
    local g, cfg, r1, r2;
    g := SymmetricGroup(5);
    cfg := rec(stabilizer := Group(()), order := CanonicalConfig_Minimum);
    r1 := CanonicalImage(g, [2,4], OnSets, cfg);
    r2 := CanonicalImage(g, [2,4], OnSets, cfg);
    if r1 <> r2 then
        Print("options record not reusable on the set path\n");
    fi;
    r1 := CanonicalImage(g, Transformation([3,3,4,4]), OnPoints, cfg);
    r2 := CanonicalImage(g, Transformation([3,3,4,4]), OnPoints, cfg);
    if r1 <> r2 then
        Print("options record not reusable on the transformation path\n");
    fi;
    cfg := rec(getStab := true);
    r1 := CanonicalImage(g, [2,4], OnSets, cfg);
    # the native engine deposits a subgroup stabilizing the canonical image
    # (the vole engine gives Stabilizer(G, O, A) of the input instead)
    if not IsBound(cfg.stab)
       or not IsSubgroup(Stabilizer(g, r1, OnSets), cfg.stab) then
        Print("getStab did not deposit a stabilizer subgroup\n");
    fi;
    r2 := CanonicalImage(g, [2,4], OnSets, cfg);
    if r1 <> r2 then
        Print("options record not reusable after getStab\n");
    fi;
end;;

_bruteMinimalPair := function(G, O, F, ordered)
    local best, g, cand;
    best := fail;
    for g in G do
        cand := [F(O[1], g), F(O[2], g)];
        if not ordered then
            Sort(cand);
        fi;
        if best = fail or cand < best then
            best := cand;
        fi;
    od;
    return best;
end;;

CheckMinimalImagePairs := function()
    local i, g, n, o, F, pairs;
    for i in [1..FERRET_TEST_LIMIT.count] do
        g := randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize]));
        if Size(g) > FERRET_TEST_LIMIT.bruteForceLimit then
            continue;
        fi;
        n := Maximum(LargestMovedPoint(g), 2);
        pairs := [
            [OnPoints, [Random([1..n + 2]), Random([1..n + 2])]],
            [OnSets, [RandomSet(n), RandomSet(n)]],
            [OnTuples, [Shuffle(RandomSet(n)), Shuffle(RandomSet(n))]]];
        for o in pairs do
            F := o[1];
            o := o[2];
            if MinimalImageOrderedPair(g, o, F)
               <> _bruteMinimalPair(g, o, F, true) then
                Print(GeneratorsOfGroup(g), " ", o, " ", F,
                      " wrong minimal ordered pair\n");
            fi;
            if MinimalImageUnorderedPair(g, o, F)
               <> _bruteMinimalPair(g, o, F, false) then
                Print(GeneratorsOfGroup(g), " ", o, " ", F,
                      " wrong minimal unordered pair\n");
            fi;
        od;
        # the OnPoints default
        o := pairs[1][2];
        if MinimalImageOrderedPair(g, o) <> _bruteMinimalPair(g, o, OnPoints, true)
           or MinimalImageUnorderedPair(g, o)
              <> _bruteMinimalPair(g, o, OnPoints, false) then
            Print(GeneratorsOfGroup(g), " ", o, " wrong 2-argument pair image\n");
        fi;
    od;
end;;

_bruteAllMinimalPairs := function(G, n, ordered)
    local ts, out, a, b, cand;
    ts := List(Tuples([1..n], n), Transformation);
    out := [];
    for a in ts do
        for b in ts do
            cand := [a, b];
            if not ordered then
                Sort(cand);
            fi;
            if _bruteMinimalPair(G, cand, OnPoints, ordered) = cand then
                AddSet(out, cand);
            fi;
        od;
    od;
    return out;
end;;

CheckAllMinimalPairs := function()
    local g, n;
    for g in [SymmetricGroup(3), Group((1,2,3)), Group((1,2)), Group(())] do
        n := 3;
        if Set(AllMinimalOrderedPairs(g, n, acceptTransform(n, n)))
           <> _bruteAllMinimalPairs(g, n, true) then
            Print(g, " wrong AllMinimalOrderedPairs\n");
        fi;
        if Set(AllMinimalUnorderedPairs(g, n, acceptTransform(n, n)))
           <> _bruteAllMinimalPairs(g, n, false) then
            Print(g, " wrong AllMinimalUnorderedPairs\n");
        fi;
    od;
end;;

FindAllMinimalImagesSetSlow := function(G, maxpnt, size)
    return Filtered(Combinations([1..maxpnt], size), 
        function(x)
            return IsMinimalImage(G, x, OnSets);
        end);
end;

CheckFindAllMinimalImages := function()
    local i, grp, min1, min2, size;
    for i in [1..FERRET_TEST_LIMIT.count] do
        size := Random([1..3]);
        grp := randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize]));
        min1 :=  AllMinimalSetsFiltered(grp, LargestMovedPoint(grp), acceptSetOfSize(LargestMovedPoint(grp), size) );
        min2 := FindAllMinimalImagesSetSlow(grp, LargestMovedPoint(grp), size);
        if min1 <> min2 then
            Print(grp, ":", size, "::\n", min1, "\n", min2, "\n");
        fi;
    od;
end;

checkCanonicalImageAtoms := function()
    local i;
    CheckCanonicalImageTest(Group(()), 1, OnFundamental);
    CheckCanonicalImageTest(Group((1,2,3)), 3, OnFundamental);
    CheckCanonicalImageTest(Group(()), 7, OnFundamental);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckCanonicalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])), 
                              Random([1..FERRET_TEST_LIMIT.groupSize + 2]), OnFundamental);
    od;
end;

checkCanonicalImageMultiset := function()
    local i, f;
    f := Combinatorial.Multiset;
    CheckCanonicalImageTest(Group(()), f([1]), OnFundamental);
    CheckCanonicalImageTest(Group((1,2,3)), f([2,3]), OnFundamental);
    CheckCanonicalImageTest(Group(()), f([7]), OnFundamental);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckCanonicalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])), 
                              Random([1..FERRET_TEST_LIMIT.groupSize + 2]), OnFundamental);
    od;
end;

checkCanonicalImageTuple := function()
    local i, f;
    f := Combinatorial.Tuple;
    CheckCanonicalImageTest(Group(()), f([1]), OnFundamental);
    CheckCanonicalImageTest(Group((1,2,3)), f([2,3]), OnFundamental);
    CheckCanonicalImageTest(Group(()), f([7]), OnFundamental);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckCanonicalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])), 
                              f(List([1..FERRET_TEST_LIMIT.groupSize], x -> Random([1..FERRET_TEST_LIMIT.groupSize + 2]))), OnFundamental);
    od;
end;

checkCanonicalImagePermutation := function()
    local i, f;
    f := Combinatorial.Permutation;
    CheckCanonicalImageTest(Group(()), f( () ), OnFundamental);
    CheckCanonicalImageTest(Group((1,2,3)), f( (1,2) ), OnFundamental);
    CheckCanonicalImageTest(Group(()), f( (1,7) ), OnFundamental);
    for i in [1..FERRET_TEST_LIMIT.count] do
        CheckCanonicalImageTest(randomGroup(Random([2..FERRET_TEST_LIMIT.groupSize])), 
                              f(Random(SymmetricGroup(FERRET_TEST_LIMIT.groupSize))), OnFundamental);
    od;
end;
