#############################################################################
##
#W  files.gi                   images Package                  Chris Jefferson
##
##  Installation file for SmallestImage.
##
#Y  Copyright (C) 2014      University of St. Andrews, North Haugh,
#Y                          St. Andrews, Fife KY16 9SS, Scotland
##

# In practice there is one interesting function here --
# smallest image for sets, which is defined in nsi.g. Everything
# else is transformed into a problem on sets, and then solved.

# Copied from Ferret (where it is called _FerretHelperFuncs)
_ImageHelperFuncs := MakeImmutable(rec(

  # Simple helper to support optional arguments
  optArg := function(Val, default)
    if Length(Val) = 0 then
      return default;
    fi;
    if Length(Val) = 1 then
      return Val[1];
    fi;
    ErrorNoReturn("Only one optional argument!");
  end,

# Copies 'useroptions' over values of 'options' with the same name.
fillUserValues := function(options, useroptions)
  local name, ret;
  ret := rec();

  useroptions := ShallowCopy(useroptions);

  for name in RecNames(options) do
    if IsBound(useroptions.(name)) then
      ret.(name) := useroptions.(name);
      Unbind(useroptions.(name));
    else
      ret.(name) := options.(name);
    fi;
  od;

  if useroptions <> rec() then
    if IsBound(useroptions.branch) then
      # a CanonicalConfig_* record passed as the whole options record
      ErrorNoReturn("Unknown options: ", RecNames(useroptions),
                    " (this looks like an ordering; did you mean",
                    " rec(order := ...)?)");
    fi;
    ErrorNoReturn("Unknown options: ", RecNames(useroptions),
                  " (valid options are: ", RecNames(options), ")");
  fi;

  return ret;
 end));

# Creates the group on a 2D matrix of x*x points
# Which is generated by swapping
# columns i&j and rows i&j simultaneously.
_rowColGen := function( inGroup, x )
  local i,j,l,p, generators, temp;

  if IsTrivial(inGroup) then
     return inGroup;
  fi;

  generators := [];
  for p in GeneratorsOfGroup(inGroup) do
    l := [];
    for i in [1..x] do
      for j in [1..x] do
        l[i+ (j-1)*x] := i^p + (j^p - 1)*x;
      od;
    od;

    Add(generators, PermList(l));
  od;

  temp:= Group(generators,());
  SetSize(temp, Size(inGroup));
  return temp;
end;

_minOrbBuilder := function(select)
    local Func;
    Func := function( G )
        local vals, order, branch;
        if LargestMovedPoint(G) = 0 then
            return ();
        fi;
        vals := Set([1..LargestMovedPoint(G)]);
        order := [];
        while vals <> [] do
            branch := select(G, vals);
            G := Stabilizer(G, branch);
            SubtractSet(vals, [branch]);
            Add(order, branch);
        od;
        return PermList(order)^-1;
    end;

    return Func;
end;



InstallMethod(MinOrbitPerm, [IsPermGroup],
    _minOrbBuilder(
        function(G, vals)
            local orbs, o, smallOrbSize, first;
            orbs := Orbits(G, vals);
            orbs := List(orbs, Set);
            orbs := Set(orbs);
            smallOrbSize := Minimum(List(orbs, Size));
            first := First(orbs, x -> Size(x) = smallOrbSize);
            return first[1];
        end
));

InstallMethod(MaxOrbitPerm, [IsPermGroup],
    _minOrbBuilder(
        function(G, vals)
            local orbs, o, largeOrbSize, first;
            orbs := Orbits(G, vals);
            orbs := List(orbs, Set);
            orbs := Set(orbs);
            largeOrbSize := Maximum(List(orbs, Size));
            first := First(orbs, x -> Size(x) = largeOrbSize);
            return first[1];
        end
));

# Install the two most common cases of rowColGen
# as an attribute
InstallMethod(rowcolsquareGroup, [IsPermGroup],
function( inGroup )
  return _rowColGen(inGroup, LargestMovedPoint(inGroup));
end);

# Install the two most common cases of rowColGen
# as an attribute
InstallMethod(rowcolsquareGroup2, [IsPermGroup],
function( inGroup )
  return _rowColGen(inGroup, LargestMovedPoint(inGroup) + 1);
end);


_booleaniseList := function(l, matrixMax)
  local set, i;
  set := [];
  for i in [1..Length(l)] do
      if IsBound(l[i]) then
          Add(set, (i-1)*matrixMax + l[i]);
      fi;
  od;
  return set;
end;

_unbooleaniseList := function(s, matrixMax)
  local lresult, img, dom, i;
  lresult := [];
  # Turn back into a partial function
  # we only feed in those values which we generated.
  for i in [1..Length(s)] do
    img := (s[i] - 1) mod matrixMax + 1;
    dom := (s[i] - img)/matrixMax + 1;
    lresult[dom] := img;
  od;

  return lresult;
end;

_CanonicalSetImage := function(G, S, stab, settings)
    local L, earlyskip, order;

    # The early-exit tests inside _NewSmallestImage compare the point
    # branched on at depth d against the d-th smallest element of S, which
    # assumes the image is selected in increasing order. That only holds
    # for the "minimum" ordering: the dynamic orderings deliberately branch
    # on rare orbits first, so a GetBool query there must compute the full
    # image and compare at the end.
    order := settings.order;
    if IsString(order) then
        order := ValueGlobal(order);
    fi;
    earlyskip := settings.result = GetBool and order.branch = "minimum";

    L := _NewSmallestImage(G, S, stab, x -> x, [earlyskip, S], settings.disableStabilizerCheck, settings.order );

    if settings.getStab then
        settings.original.stab := L[2];
    fi;

    if L[1] = false then
        return false;
    fi;

    if settings.result = GetImage then
        return L[1];
    fi;

    if settings.result = GetBool then
        if L[1] = MinImage.Smaller or L[1] = MinImage.Larger then
            return false;
        else
            return Set(L[1]) = Set(S);
        fi;
    fi;

    if settings.result = GetPerm then
        if IsPermGroup(G) then
            return RepresentativeAction(G, S, L[1], OnTuples);
        fi;
        # G is a group interface record
        return G.repAction(S, L[1]);
    fi;

    ErrorNoReturn("Invalid value of result");
end;


InstallGlobalFunction("IsMinimalImageLessThan",
    function(G, A, B, extra...)
        local ret;
        B := Set(B);
        if Length(extra) <> 1 or extra[1] <> OnSets then
            ErrorNoReturn("IsMinimalImageLessThan only supports the action OnSets");
        fi;
        if Length(A) <> Length(B) then
            ErrorNoReturn("IsMinimalImageLessThan only supports sets of equal size");
        fi;
        ret := _NewSmallestImage(G, A, Stabilizer(G, A, OnSets), x -> x, [true, Set(B)], false, CanonicalConfig_Minimum);
        if ret[1] = MinImage.Smaller or ret[1] = MinImage.Larger then
            return ret[1];
        fi;
        ret[1] := Set(ret[1]);
        if ret[1] < B then
            return MinImage.Smaller;
        elif ret[1] > B then
            return MinImage.Larger;
        else
            return MinImage.Equal;
        fi;
end);

_CanonicalSetSetImage := function(G, S, stab, stepval, settings)
    local L;

    # Sets of sets are always canonicalised in the minimum order; the
    # blockSize option makes _NewSmallestImage minimise under the blocked
    # ordering, which matches GAP's ordering of sets of sets.
    L := _NewSmallestImage(G, S, stab, x -> x, [false],
                           settings.disableStabilizerCheck,
                           rec(branch := "minimum", blockSize := stepval));

    if settings.result = GetImage then
        return L[1];
    fi;

    if settings.result = GetBool then
        return Set(L[1]) = Set(S);
    fi;

    if settings.result = GetPerm then
        # G is a group interface record
        return G.repAction(S, L[1]);
    fi;

    ErrorNoReturn("Invalid value of result");
end;

_CanonicalTupleSetImage := function(G, origS, settings)
    local i, stab, curperm, curset, L, perm, S, Slen;
    curperm := ();
    if settings.order <> CanonicalConfig_Minimum then
        S := Filtered(origS, x -> Length(x) > 0);
        Slen := List(S, Length);
        SortParallel(Slen, S);
    else
        S := origS;
    fi;

    for i in [1..Length(S)] do
        curset := OnSets(S[i], curperm);
        stab := Stabilizer(G, curset, OnSets);
        L := _NewSmallestImage(G, curset, stab, x->x, [false], settings.disableStabilizerCheck, settings.order );
        perm := RepresentativeAction(G, curset, L[1], OnTuples);
        curperm := curperm * perm;
        G := stab^perm;
    od;

    if settings.result = GetImage then
        return OnTuplesSets(origS, curperm);
    fi;

    if settings.result = GetBool then
        return OnTuplesSets(origS, curperm) = origS;
    fi;

    if settings.result = GetPerm then
        return curperm;
    fi;

    ErrorNoReturn("Invalid value of result");
end;






# Ferret is an optional dependency which can compute the stabilizer of a
# set of pairs directly in the natural action of G
_ImagesFerretGlobals := function()
  if IsPackageLoaded("ferret") then
    return rec(solve := ValueGlobal("Solve"),
               conInGroup := ValueGlobal("ConInGroup"),
               conStabilize := ValueGlobal("ConStabilize"));
  fi;
  return fail;
end;

# The stabilizer in G of a set of encoded pairs, returned as a subgroup of G
# in its natural action (the pair action is faithful, so this is
# well-defined).
_IMAGES_PairSetStabilizer := function(G, set, mMax)
  local ferret, pairs, rowcolGroup, bigstab, gens, result;

  ferret := _ImagesFerretGlobals();
  if ferret <> fail then
    pairs := Set(set, function(p)
        local r;
        r := (p - 1) mod mMax + 1;
        return [r, (p - r)/mMax + 1];
    end);
    return ferret.solve([ferret.conInGroup(G),
                         ferret.conStabilize(pairs, OnSetsTuples)]);
  fi;

  # Without ferret, fall back on a backtrack search in the explicit
  # row-column group on mMax^2 points, and project the result back to G.
  # This is far slower for large mMax; loading ferret avoids it.
  # Cache only the most common group
  if mMax = LargestMovedPoint(G) then
    rowcolGroup := rowcolsquareGroup(G);
  elif mMax = LargestMovedPoint(G) + 1 then
    rowcolGroup := rowcolsquareGroup2(G);
  else
    rowcolGroup := _rowColGen(G, mMax);
  fi;
  bigstab := Stabilizer(rowcolGroup, set, OnSets);
  # The image of the diagonal cell (x,x) under the row-column permutation
  # of g is (x^g, x^g), from which we read off g itself
  gens := List(GeneratorsOfGroup(bigstab),
               b -> PermList(List([1..mMax],
                                  x -> ((x + (x-1)*mMax)^b - 1) mod mMax + 1)));
  result := Group(gens, ());
  SetSize(result, Size(bigstab));
  return result;
end;

# When the orbit of the object is small, enumerating it directly is far
# cheaper than the stabilizer-chain search: the search must build chains
# for G (and for the supplied stabilizer's position action), which for
# groups with deep chains costs minutes while a small orbit enumerates in
# milliseconds. This pre-pass runs the orbit BFS with kernel list
# arithmetic, minimising exactly the set order the search minimises, and
# answers the query if the orbit closes within a work budget, returning
# fail otherwise (for GetImage the answer is the encoded set). The set
# need not be a partial function (a partial permutation's bound pairs, a
# digraph's arcs): all sets in one orbit have the same size, so the
# sorted-list comparison never reaches the proper-prefix case.
#
# It only fires for branch="minimum" orders: there the answer is the true
# minimum of the orbit, so it agrees exactly with the search on every
# combination of options (a getStab call, which returns fail here and
# falls through to the search, still gets the same image).
_IMAGES_PairSmallOrbit := function(l, set, G, mMax, settings)
    local order, gens, glists, ginvlists, dense, actGen, actBy, k, hash,
          dict, queue, parents, gennos, cap, i, j, im, minpos, perm;

    if settings.getStab then
        return fail;
    fi;
    order := settings.order;
    if IsString(order) then
        order := ValueGlobal(order);
    fi;
    if not (IsRecord(order) and IsBound(order.branch)
            and order.branch = "minimum") then
        return fail;
    fi;

    gens := GeneratorsOfGroup(G);
    glists := List(gens, g -> ListPerm(g, mMax));
    # Orbit elements are kept as image lists when the object is total (a
    # transformation or permutation): composing image lists is much
    # cheaper than decoding and re-sorting encoded sets, and image-list
    # comparison is the encoded-set order because the encoded pairs
    # (i, l[i]) sort by row. A partial permutation's sparse set is
    # enumerated as sorted encoded sets {(r-1)*mMax + c} directly.
    dense := IsDenseList(l) and Length(l) = mMax;
    if dense then
        ginvlists := List(gens, g -> ListPerm(g^-1, mMax));
        # (e^g)[i] = ((i^(g^-1))^e)^g
        actGen := function(e, j)
            return glists[j]{ e{ ginvlists[j] } };
        end;
        actBy := function(e, p)
            return ListPerm(p, mMax){ e{ ListPerm(p^-1, mMax) } };
        end;
        queue := [Immutable(ShallowCopy(l))];
    else
        actGen := function(e, j)
            local cs, im;
            cs := (e - 1) mod mMax + 1;
            im := (glists[j]{ (e - cs) / mMax + 1 } - 1) * mMax
                  + glists[j]{ cs };
            Sort(im);
            return im;
        end;
        actBy := function(e, p)
            local rows, cs, im;
            rows := ListPerm(p, mMax);
            cs := (e - 1) mod mMax + 1;
            im := (rows{ (e - cs) / mMax + 1 } - 1) * mMax + rows{ cs };
            Sort(im);
            return im;
        end;
        queue := [Immutable(ShallowCopy(set))];
    fi;
    k := Length(set);

    # A supplied stabilizer is promised to be validated on every path
    # which consumes the option, so reject a wrong one here too, even
    # though this path never otherwise looks at it
    if settings.stabilizer <> fail then
        for perm in GeneratorsOfGroup(settings.stabilizer) do
            if actBy(queue[1], perm) <> queue[1] then
                ErrorNoReturn("the given <stabilizer> does not stabilize the object");
            fi;
        od;
    fi;

    # When the orbit is larger than the cap the whole enumeration is
    # wasted, so the budget must track what the search would otherwise
    # cost. The cost per enumerated element is a hash and dictionary
    # constant of a few microseconds plus list work proportional to
    # |set|, with the constant dominating for all but very large sets.
    # When G already has a stabilizer chain and no enormous stabilizer
    # was supplied the search is cheap, and only a small budget is
    # justified. When the chain is missing (or a supplied stabilizer is
    # so large that the search must run a Schreier-Sims on its position
    # action) the search starts with a chain construction whose cost
    # grows like a high power of mMax, and a far larger budget is still
    # cheap by comparison.
    if HasStabChainMutable(G)
       and not (settings.stabilizer <> fail
                and HasSize(settings.stabilizer)
                and Size(settings.stabilizer) > 2^60) then
        cap := Maximum(512, QuoInt(10^6, Length(gens) * (k + 100)));
    else
        cap := Maximum(1024, QuoInt(mMax^3, 30 * Length(gens)));
    fi;
    cap := Minimum(cap, 500000);

    hash := _IMAGES_Get_Hash(Length(queue[1]));
    dict := SparseHashTable(hash);
    AddHashEntry(dict, queue[1], 1);
    parents := [0];
    gennos := [0];
    minpos := 1;
    i := 1;
    while i <= Length(queue) do
        for j in [1..Length(gens)] do
            im := actGen(queue[i], j);
            if GetHashEntry(dict, im) = fail then
                if Length(queue) >= cap then
                    return fail;
                fi;
                MakeImmutable(im);
                Add(queue, im);
                Add(parents, i);
                Add(gennos, j);
                AddHashEntry(dict, im, Length(queue));
                if im < queue[minpos] then
                    minpos := Length(queue);
                fi;
            fi;
        od;
        i := i + 1;
    od;

    if settings.result = GetBool then
        return queue[minpos] = queue[1];
    elif settings.result = GetImage then
        # return the encoded set in both representations
        if dense then
            return List([1..mMax], i -> (i - 1)*mMax + queue[minpos][i]);
        fi;
        return ShallowCopy(queue[minpos]);
    fi;

    # settings.result = GetPerm: multiply out the generator word leading
    # from the root to the minimal element
    perm := ();
    i := minpos;
    while parents[i] <> 0 do
        perm := gens[gennos[i]] * perm;
        i := parents[i];
    od;
    if actBy(queue[1], perm) <> queue[minpos] then
        ErrorNoReturn("internal error in the images package (the small ",
                      "orbit pre-pass built a wrong conjugating element); ",
                      "please report this");
    fi;
    return perm;
end;

# Minimise a set of encoded pairs under the pair action of G on
# [1..mMax] x [1..mMax]. This is the common engine behind
# transformations, permutations, partial permutations and digraphs. l is
# the object as a (partial) image list when it is one, which lets the
# small-orbit pre-pass work in the cheaper image-list representation;
# any caller whose set is not a partial function must pass l = fail.
# For GetImage the ENCODED minimal set is returned; GetPerm is already
# projected into the natural action of G.
_IMAGES_MinimalImage_PairSet := function(l, set, G, mMax, settings)
  local order, result, pairGroup, stab;

  order := settings.order;
  if IsString(order) then
      order := ValueGlobal(order);
  fi;
  if IsRecord(order) and IsBound(order.branch) and order.branch = "static" then
      ErrorNoReturn("static branch orderings (such as CanonicalConfig_FixedMinOrbit) ",
                    "are not supported for transformations, permutations, ",
                    "partial permutations or digraphs");
  fi;

  result := _IMAGES_PairSmallOrbit(l, set, G, mMax, settings);
  if result <> fail then
      return result;
  fi;

  pairGroup := _IMAGES_PairActionIface(G, mMax);

  if settings.stabilizer <> fail then
     stab := settings.stabilizer;
  elif IsBound(settings.centralizerOf) then
     stab := Centralizer(G, settings.centralizerOf);
  elif IsBound(settings.stabilizerFunc) then
     stab := settings.stabilizerFunc();
  else
     stab := _IMAGES_PairSetStabilizer(G, set, mMax);
  fi;

  return _CanonicalSetImage(pairGroup, set, stab, settings);
end;

_MinimalImage_partialFunction := function(l, G, mMax, settings)
  local set, image;

  # Turn partial function into a subset of a 2D matrix,
  # which contains (i,j) if i^trans = j.
  set := _booleaniseList(l, mMax);

  image := _IMAGES_MinimalImage_PairSet(l, set, G, mMax, settings);

  if settings.result = GetImage then
      return _unbooleaniseList(image, mMax);
  fi;
  return image;
end;

# This function just encapsulates what we have to return in the case
# of a trivial input case (usually, group is the identity)
_trivialReturn := function(object, result)
    if result = GetBool then
        return true;
    elif result = GetPerm then
        return ();
    elif result = GetImage then
        return object;
    else
        ErrorNoReturn("Invalid value of result");
    fi;
end;



# Returns the minimum image of a transformation
InstallMethod(CanonicalImageOp, [IsPermGroup, IsTransformation, IsFunction, IsObject],
function(inGroup, trans, action, settings)
  local l, lresult, transformMax, matrixMax;

  if action <> OnPoints then
    ErrorNoReturn("Transformations only support the action OnPoints");
  fi;

  # Return in trivial cases
  if Maximum(LargestMovedPoint(trans),LargestImageOfMovedPoint(trans)) = 0 or
     LargestMovedPoint(inGroup) = 0 then
      return _trivialReturn(trans, settings.result);
  fi;

  # First find the largest integer of interest
  transformMax := Maximum(LargestImageOfMovedPoint(trans),
                          LargestMovedPoint(trans));

  # TODO: This could be reduced but not all the way down to
  # LargestMovedPoint(inGroup) in general.
  matrixMax := Maximum(transformMax, LargestMovedPoint(inGroup));

  # Turn transformation into function and pass to general case
  l := ListTransformation(trans, matrixMax);
  lresult := _MinimalImage_partialFunction(l, inGroup, matrixMax, settings);

  #Print(":",settings.,":",GetImage,":",settings.image = GetImage,"\n");

  if settings.result = GetImage then
      return Transformation(lresult);
  else
      return lresult;
  fi;

end);

# Returns the minimum image of a transformation
InstallMethod(CanonicalImageOp, [IsPermGroup, IsPerm, IsFunction, IsObject],
function(inGroup, trans, action, settings)
  local l, lresult, transformMax, matrixMax;

  if action <> OnPoints then
    ErrorNoReturn("Permutations only support the action OnPoints");
  fi;

  # Return in trivial cases
  if LargestMovedPoint(trans) = 0 or LargestMovedPoint(inGroup) = 0 then
      return _trivialReturn(trans, settings.result);
  fi;

  # First find the largest integer of interest
  transformMax := LargestMovedPoint(trans);

  # TODO: This could be reduced but not all the way down to
  # LargestMovedPoint(inGroup) in general.
  matrixMax := Maximum(transformMax, LargestMovedPoint(inGroup));

  # The stabilizer of the graph of a permutation is its centralizer,
  # which GAP computes faster than the generic pair stabilizer. It is
  # computed in _MinimalImage_partialFunction rather than here so that
  # the small-orbit pre-pass can answer first: Centralizer forces a
  # stabilizer chain for the group, which can cost far more than the
  # entire enumeration.
  if settings.stabilizer = fail then
      settings := ShallowCopy(settings);
      settings.centralizerOf := trans;
  fi;

  # Turn transformation into function and pass to general case
  l := ListPerm(trans, matrixMax);
  lresult := _MinimalImage_partialFunction(l, inGroup, matrixMax, settings);

  if settings.result = GetImage then
      return PermList(lresult);
  else
      return lresult;
  fi;

end);

InstallMethod(CanonicalImageOp, [IsPermGroup, IsPosInt, IsFunction, IsObject],
        function(inGroup, i, action, settings)
    local min;

    min := Minimum(Orbit(inGroup, i, action));

    if settings.result = GetImage then
        return min;
    elif settings.result = GetBool then
        return min = i;
    else #GetPerm
        return RepresentativeAction(inGroup, i, min, action);
    fi;
end);

InstallMethod(CanonicalImageOp, [IsPermGroup, IsPartialPerm, IsFunction, IsObject],
function(inGroup, pp, action, settings)
  local max, matrixMax, l, lresult, dom, i;

  if action <> OnPoints then
    ErrorNoReturn("Partial permutations only support the action OnPoints");
  fi;

  # First find the largest integer of interest
  max := Maximum(DegreeOfPartialPerm(pp),
                 CodegreeOfPartialPerm(pp));

  # Return in trivial cases
  if max = 0 then
      return _trivialReturn(pp, settings.result);
  fi;

  matrixMax := Maximum(max, LargestMovedPoint(inGroup));

  # Encode only the bound pairs, so the search works on a set the size of
  # the domain instead of the whole matrix. On sets of equal size (and
  # conjugation preserves the domain size, so a whole orbit shares one
  # size) this sparse encoding induces the same order as the older
  # encoding which totalised the partial permutation with an extra fixed
  # point: at the first row where two objects differ, a bound value beats
  # both a larger bound value and any later row. The minimal images are
  # therefore identical, and no extra point is needed.
  l := [];
  for i in DomainOfPartialPerm(pp) do
      l[i] := i^pp;
  od;

  lresult := _MinimalImage_partialFunction(l, inGroup, matrixMax, settings);

  if settings.result = GetPerm or settings.result = GetBool then
      return lresult;
  fi;

  dom := Filtered([1..matrixMax], i -> IsBound(lresult[i]));
  return PartialPerm(dom, lresult{dom});
end);

# The action of a permutation on a multiplication (Cayley) table: the
# table of the isomorphic structure on the relabelled elements, so
# OnMultiplicationTables(T, g)[i^g][j^g] = T[i][j]^g. Isomorphism of
# magmas is precisely equality up to this action.
BindGlobal("OnMultiplicationTables", function(T, g)
  local n, R, i, j;
  n := Length(T);
  R := List([1..n], i -> EmptyPlist(n));
  for i in [1..n] do
    for j in [1..n] do
      R[i^g][j^g] := T[i][j]^g;
    od;
  od;
  return R;
end);

# A multiplication table is a total function on the n^2 cells, i.e. a
# set of pairs (cell, value). G acts on cells by the pair action and on
# values naturally; that combined action is one permutation group on
# n^2 + n points, and the pair-action engine does the rest. The induced
# order is row-major comparison of the value lists, which is GAP's <
# on the tables themselves.
_IMAGES_TableLift := function(G, n)
  local m, hgens, g, p, i, j, H;
  m := n^2 + n;
  hgens := [];
  for g in GeneratorsOfGroup(G) do
    p := [];
    for i in [1..n] do
      for j in [1..n] do
        p[(i-1)*n + j] := (i^g - 1)*n + j^g;
      od;
    od;
    for i in [1..n] do
      p[n^2 + i] := n^2 + i^g;
    od;
    Add(hgens, PermList(p));
  od;
  H := Group(hgens, ());
  # the value coordinate is the natural action, so the lift is faithful
  SetSize(H, Size(G));
  return H;
end;

_IMAGES_TableImage := function(G, T, settings)
  local n, m, H, set, res, minT, i, j, c, v;
  n := Length(T);
  if not ForAll(T, row -> IsList(row) and Length(row) = n
                          and ForAll(row, x -> IsPosInt(x) and x <= n)) then
    ErrorNoReturn("OnMultiplicationTables requires an n x n table ",
                  "with entries in [1..n]");
  fi;
  if LargestMovedPoint(G) > n then
    ErrorNoReturn("the group moves points beyond the domain of the table");
  fi;

  m := n^2 + n;
  H := _IMAGES_TableLift(G, n);
  # cheap at this degree with the order already known, and it tells the
  # small-orbit pre-pass to keep its probe budget small
  StabChainMutable(H);

  if settings.stabilizer <> fail then
      # lift the supplied stabilizer to H; every consuming path
      # validates it against the encoded set as usual
      settings := ShallowCopy(settings);
      settings.stabilizer := _IMAGES_TableLift(settings.stabilizer, n);
  fi;

  set := [];
  for i in [1..n] do
    for j in [1..n] do
      Add(set, ((i-1)*n + j - 1)*m + n^2 + T[i][j]);
    od;
  od;

  res := _IMAGES_MinimalImage_PairSet(fail, set, H, m, settings);

  if settings.result = GetBool then
      return res;
  elif settings.result = GetPerm then
      # res lives in H; read the underlying permutation off the values
      return PermList(List([1..n], i -> (n^2 + i)^res - n^2));
  fi;
  minT := List([1..n], i -> EmptyPlist(n));
  for i in [1..Length(res)] do
      v := (res[i] - 1) mod m + 1 - n^2;
      c := (res[i] - (v + n^2))/m + 1;
      minT[QuoInt(c - 1, n) + 1][(c - 1) mod n + 1] := v;
  od;
  return minT;
end;

# A digraph's arcs are a set of pairs on its vertices, so digraphs run
# through the same pair-action engine as transformations: the arc (u,v)
# encodes to (u-1)*n + v, and the whole arc set is minimised at once.
# The induced order compares the sorted arc lists lexicographically
# (which is neither GAP's < on digraphs nor the lexicographic order on
# adjacency matrices read as 0/1 strings). Undirected graphs are
# symmetric digraphs and need no separate treatment.
InstallMethod(CanonicalImageOp, [IsPermGroup, IsDigraph, IsFunction, IsObject],
function(inGroup, digraph, action, settings)
  local n, set, result, arcs;

  if action <> OnDigraphs and action <> OnPoints then
    ErrorNoReturn("Digraphs only support the action OnDigraphs");
  fi;
  if IsMultiDigraph(digraph) then
    ErrorNoReturn("CanonicalImage does not support multidigraphs");
  fi;

  n := DigraphNrVertices(digraph);
  if LargestMovedPoint(inGroup) > n then
    ErrorNoReturn("the group moves points beyond the vertices of the digraph");
  fi;

  set := Set(DigraphEdges(digraph), e -> (e[1] - 1)*n + e[2]);

  # Return in trivial cases (the search rejects empty sets)
  if Length(set) = 0 or LargestMovedPoint(inGroup) = 0 then
      return _trivialReturn(digraph, settings.result);
  fi;

  # When the group is the full symmetric group on the vertices, the
  # stabilizer of the arc set is the automorphism group of the digraph,
  # which bliss computes far faster than the generic pair stabilizer.
  # It is computed lazily so the small-orbit pre-pass can answer first.
  if settings.stabilizer = fail and IsNaturalSymmetricGroup(inGroup)
     and MovedPoints(inGroup) = [1..n] then
      settings := ShallowCopy(settings);
      settings.stabilizerFunc := {} -> AutomorphismGroup(digraph);
  fi;

  result := _IMAGES_MinimalImage_PairSet(fail, set, inGroup, n, settings);

  if settings.result <> GetImage then
      return result;
  fi;

  arcs := List(result, function(p)
      local c;
      c := (p - 1) mod n + 1;
      return [(p - c)/n + 1, c];
  end);
  return DigraphByEdges(arcs, n);
end);


_cajGroupCopy := function(G, max, copies)
  local result, gen, i, j, p;

  result := [];
  for gen in GeneratorsOfGroup(G) do
    p := [];
    for i in [0..copies-1] do
      for j in [1..max] do
        p[j+i*max] := j^gen + i*max;
      od;
    od;
    Add(result, PermList(p));
  od;

  return GroupByGenerators(result, ());
end;

# WreathProduct doesn't quite give us the control we need
# (we can't set how big a copy of G to max for example)
_cajWreath := function(G, max, copies)
  local result, gen, i, j, p;

  result := List(GeneratorsOfGroup(_cajGroupCopy(G, max, copies)));

  Add(result, PermList(Flat([ [max+1..max*2], [1..max]])));
  Add(result, PermList(Flat([ [max+1..max*copies], [1..max]])));

  return GroupByGenerators(result, ());
end;

# The stabilizer of the set of sets fList, as permutations of the encoded
# domain of nBlocks blocks of mMax points (the domain of
# _IMAGES_SetSetActionIface). Each element's block part is determined by
# its action on the inner sets, so ferret can find the stabilizer in the
# natural action of G, and each generator lifts to the encoded domain.
_IMAGES_SetSetStabilizer := function(G, fList, setImage, mMax, nBlocks)
  local ferret, natstab, lifted, g, sigmaList, row, l, b, result;

  ferret := _ImagesFerretGlobals();
  # Duplicated inner sets would need a multiset matching below; they are
  # degenerate enough to just take the slow path.
  if ferret = fail or not IsDuplicateFreeList(fList) then
    # Backtrack search in the explicit group on mMax*nBlocks points.
    # This is far slower for large domains; loading ferret avoids it.
    return Stabilizer(_cajWreath(G, mMax, nBlocks), setImage, OnSets);
  fi;

  natstab := ferret.solve([ferret.conInGroup(G),
                           ferret.conStabilize(Set(fList), OnSetsSets)]);
  lifted := [];
  for g in GeneratorsOfGroup(natstab) do
    sigmaList := List(fList, s -> Position(fList, OnSets(s, g)));
    if fail in sigmaList then
      ErrorNoReturn("panic: stabilizer generator does not stabilize the set of sets");
    fi;
    row := ListPerm(g, mMax);
    l := EmptyPlist(mMax*nBlocks);
    for b in [1..nBlocks] do
      Append(l, row + (sigmaList[b] - 1)*mMax);
    od;
    Add(lifted, PermList(l));
  od;
  result := Group(lifted, ());
  # g determines the block part, so the lift is an isomorphism
  SetSize(result, Size(natstab));
  return result;
end;



# This handles some trivial cases (OnSets, OnTuples)
# and some non-trival ones too!
InstallMethod(CanonicalImageOp, [IsPermGroup, IsList, IsFunction, IsObject],
function(inGroup, inList, op, settings)
  local stab, maxIn, setImage, imageperm, currentperm, i, outset, inner, outer, fList;

  # Bail out in global trivial case:
  if LargestMovedPoint(inGroup) = 0 then
    return _trivialReturn(inList, settings.result);
  fi;

  if op = OnSets then
      if settings.stabilizer <> fail then
          stab := settings.stabilizer;
          # a group is a subgroup of the stabilizer iff its generators
          # preserve the set, so this check is cheap and complete
          if not ForAll(GeneratorsOfGroup(stab), g -> OnSets(inList, g) = inList) then
              ErrorNoReturn("the given <stabilizer> does not stabilize the object");
          fi;
      else
          stab := Stabilizer(inGroup, inList, OnSets);
      fi;

      imageperm := _CanonicalSetImage(inGroup, inList, stab, settings);
      if settings.result = GetImage then
         return Set(imageperm);
      else
         return imageperm;
      fi;

  fi;

  if op = OnTuples then
      fList := [];
      currentperm := ();
      for i in [1..Length(inList)] do
          imageperm := MinimalImagePerm(inGroup, inList[i]^currentperm, OnPoints);
          currentperm := currentperm*imageperm;
          fList[i] := inList[i]^currentperm;
          inGroup := Stabilizer(inGroup, fList[i]);
      od;
      if settings.result = GetImage then
          return fList;
      elif settings.result = GetBool then
          return fList = inList;
      else # GetPerm
          return currentperm;
      fi;
  fi;

  if op = OnTuplesSets then
    return _CanonicalTupleSetImage(inGroup, inList, settings);
  fi;

  if op = OnMultiplicationTables then
    return _IMAGES_TableImage(inGroup, inList, settings);
  fi;

  if op = OnSetsSets then
    # Our code is not happy with empty lists, so let's get them filtered out first
    # (we will add them back at the end)
    fList := Filtered(inList, x -> Length(x) > 0);

    # Bail out in trivial situation
    if Length(fList) = 0 then
      return _trivialReturn(inList, settings.result);
    fi;

    maxIn := Maximum(Maximum(List(fList, x -> Maximum(x))),
                     LargestMovedPoint(inGroup));

    setImage := Flat(List([1..Length(fList)],
                        x -> List(fList[x], y -> y + (x-1)*maxIn)));
    if settings.stabilizer <> fail then
        if IsTrivial(settings.stabilizer) then
            stab := Group(());
        else
            ErrorNoReturn("Only the trivial group may be given as the <stabilizer> ",
                  "option for the action OnSetsSets");
        fi;
    else
        stab := _IMAGES_SetSetStabilizer(inGroup, fList, setImage,
                                         maxIn, Length(fList));
    fi;

    imageperm := _CanonicalSetSetImage(
        _IMAGES_SetSetActionIface(inGroup, maxIn, Length(fList)),
        setImage, stab, maxIn, settings);

    if settings.result = GetBool then
        return imageperm;
    fi;

    if settings.result = GetPerm then
        # repAction already projected the answer into the natural action
        return imageperm;
    fi;

    outset := List([1..Length(fList)], x -> []);

    for i in imageperm do
      inner := (i - 1) mod maxIn + 1;
      outer := (i - inner)/maxIn + 1;
      Add(outset[outer], inner);
    od;

    # Put those filtered lists back in
    for i in [1..Length(inList) - Length(fList)] do
      Add(outset, []);
    od;

    return Set(outset, x -> Set(x));
  fi;

  ErrorNoReturn("Unsupported action ", NameFunction(op), " on a list: the ",
                "supported actions are OnSets, OnTuples, OnSetsSets, ",
                "OnTuplesSets and OnMultiplicationTables");

end);

# Vole is an optional dependency; raise a clear error if it is not loaded
_ImagesVoleGlobals := function(why)
  if not IsBoundGlobal("VoleFind") then
    ErrorNoReturn(why, " requires the 'vole' package, which could not be ",
                "loaded; please install vole (https://github.com/peal/vole), then ",
                "load it with LoadPackage(\"vole\")");
  fi;
  return rec(find := ValueGlobal("VoleFind"),
             constraint := ValueGlobal("Constraint"));
end;

# Compute a canonical image using Vole (via VoleFind.Canonical) instead of the
# native algorithm. Vole finds *a* canonical image; it cannot produce the
# lexicographically minimal image, so this rejects minimal-image requests.
_VoleCanonicalImage := function(G, obj, action, settings)
  local vole, ret;

  if IsBound(settings.order) and IsRecord(settings.order)
     and IsBound(settings.order.branch) and settings.order.branch = "minimum" then
    ErrorNoReturn("The 'vole' engine cannot compute minimal images (only canonical images)");
  fi;

  vole := _ImagesVoleGlobals("Finding canonical images with 'vole'");
  ret := vole.find.Canonical(G, vole.constraint.Stabilize(obj, action));

  if settings.getStab then
    settings.original.stab := ret.group;
  fi;

  if settings.result = GetPerm then
    return ret.canonical;
  elif settings.result = GetImage then
    return action(obj, ret.canonical);
  elif settings.result = GetBool then
    # obj is its own canonical image iff applying the canonical perm is a no-op.
    return action(obj, ret.canonical) = obj;
  fi;

  ErrorNoReturn("Invalid value of result");
end;

InstallGlobalFunction(_CanonicalImageParse, function ( arglist, resultarg, imagearg )
  local G,        # Group
        obj,      # object
        action,   # action
        settings, # settings
        index;    # index

  if Length(arglist) < 2 or Length(arglist) > 4 then
    ErrorNoReturn("usage: MinimalImage/CanonicalImage(G, obj [, action] [, config])");
  fi;

  G := arglist[1];

  if not(IsPermGroup(G)) then
    ErrorNoReturn("First argument must be a permutation group");
  fi;

  obj := arglist[2];

  index := 3;

  if Length(arglist) >= index and IsFunction(arglist[index]) then
    action := arglist[3];
    index := index + 1;
  else
    action := OnPoints;
  fi;

  # 'stab' is where the getStab option deposits its answer, in the record the
  # user passed; accepting it here lets the same record be passed to a
  # second call
  settings := rec(result := resultarg, stabilizer := fail, order := imagearg, getStab := false,
                  disableStabilizerCheck := false, engine := "native", stab := fail);

  if Length(arglist) >= index and IsRecord(arglist[index]) then
    settings := _ImageHelperFuncs.fillUserValues(settings, arglist[index]);
    settings.original := arglist[index];
    index := index + 1;
  fi;

  if index <= Length(arglist) then
    ErrorNoReturn("Failed to understand argument ", index, ", which was ", arglist[index]);
  fi;

  if settings.engine = "vole" then
    return _VoleCanonicalImage(G, obj, action, settings);
  elif settings.engine <> "native" then
    ErrorNoReturn("Unknown engine '", settings.engine, "': must be \"native\" or \"vole\"");
  fi;

  return CanonicalImageOp(G, obj, action, settings);
end);

InstallGlobalFunction(MinimalImage, function(arg)
  return _CanonicalImageParse(arg, GetImage, CanonicalConfig_Minimum);
end);

InstallGlobalFunction(IsMinimalImage, function(arg)
  return _CanonicalImageParse(arg, GetBool, CanonicalConfig_Minimum);
end);

InstallGlobalFunction(MinimalImagePerm, function(arg)
  return _CanonicalImageParse(arg, GetPerm, CanonicalConfig_Minimum);
end);

InstallGlobalFunction(CanonicalImage, function(arg)
  return _CanonicalImageParse(arg, GetImage, CanonicalConfig_Fast);
end);

InstallGlobalFunction(IsCanonicalImage, function(arg)
  return _CanonicalImageParse(arg, GetBool, CanonicalConfig_Fast);
end);

InstallGlobalFunction(CanonicalImagePerm, function(arg)
  return _CanonicalImageParse(arg, GetPerm, CanonicalConfig_Fast);
end);



InstallMethod(MinimalImageOrderedPair, [IsPermGroup, IsObject],
  function(G,O) return MinimalImageOrderedPair(G,O,OnPoints);
end);

InstallMethod(MinimalImageOrderedPair, [IsPermGroup, IsList, IsFunction],
  function(G, O, F)
    local fperm, first;

    fperm := MinimalImagePerm(G, O[1], F);
    first := F(O[1], fperm);
    return [first, MinimalImage(Stabilizer(G, first, F), F(O[2], fperm), F)];
end);

InstallMethod(MinimalImageUnorderedPair, [IsPermGroup, IsObject],
  function(G,O) return MinimalImageUnorderedPair(G,O,OnPoints);
end);

InstallMethod(MinimalImageUnorderedPair, [IsPermGroup, IsList, IsFunction],
  function(G, O, F)
    local fperm, sperm, first, second, act1, act2;

    fperm := MinimalImagePerm(G, O[1], F);
    sperm := MinimalImagePerm(G, O[2], F);

    act1 := F(O[1], fperm);
    act2 := F(O[2], sperm);

    if act1 < act2 then
        second := MinimalImage(Stabilizer(G, F(O[1], fperm), F), F(O[2], fperm), F);
        return [F(O[1], fperm), second];
    fi;

    if act1 > act2 then
        first := MinimalImage(Stabilizer(G, F(O[2], sperm), F), F(O[1], sperm), F);
        return [F(O[2], sperm), first];
    fi;

     second := MinimalImage(Stabilizer(G, F(O[1], fperm), F), F(O[2], fperm), F);
     first := MinimalImage(Stabilizer(G, F(O[2], sperm), F), F(O[1], sperm), F);

     if first < second then
         return [act1, first];
     else
         return [act1, second];
     fi;
 end);


## CanonicalImage(Group, Obj, rec(action:=OnSets,
##                                image:="Minimal",
##                                result := GetBool/GetBool/GetImage));
